icons_format = "{icon}"

[theme.overrides]
# Example: redefine `idle` colors
idle_fg = "#ffffff"

[[block]]
block = "custom"
command = "cat /sys/class/power_supply/macsmc-battery/capacity"
interval = 1

[[block]]
block = "net"
format = " $icon ( $signal_strength at $ssid ) $ip"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
interval = 1
format = " $icon $barchart $utilization "

[[block]]
block = "memory"
format = " $icon $mem_avail.eng(w:3,u:B,p:Mi) / $mem_total.eng(w:3,u:B,p:Mi) "

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = " $icon $timestamp.datetime(f:'%m-%d-%Y %I:%M %p') "
